### ISSUE TITLE
postprocessing after the last iteration fails...

### ISSUE THREAD

**Issue by MHeinrichs** [DLR-TS/tsc#23]
After finishing the last iteration we get the following:
 
 Error: gap in edge sequence at trip 102631480_101510062_1040_0
 Error: gap in edge sequence at trip 100731064_100430129_808_0
 Error: gap in edge sequence at trip 100924532_100533830_851_0
 Error: gap in edge sequence at trip 102355056_101349056_1140_0
 Error: gap in edge sequence at trip 102721114_101558179_1103_0
 Error: gap in edge sequence at trip 100993085_100576008_1351_0
 Error: gap in edge sequence at trip 100257717_100162228_423_0
 Error: gap in edge sequence at trip 100257717_100162228_900_0
 Error: gap in edge sequence at trip 100257717_100162228_1219_0
 Error: gap in edge sequence at trip 100945464_100549503_1101_0
 Error: gap in edge sequence at trip 102102443_101206967_877_0
 Error: gap in edge sequence at trip 102102443_101206967_1143_0
 Error: gap in edge sequence at trip 102102443_101206967_1290_0
 Error: gap in edge sequence at trip 102431733_101401158_370_0
 Error: gap in edge sequence at trip 102431733_101401158_1248_0
 Error: gap in edge sequence at trip 102431733_101401158_1276_0
 Error: gap in edge sequence at trip 102035941_101170435_945_0
 Error: gap in edge sequence at trip 102035941_101170435_978_0
 Error: gap in edge sequence at trip 103172085_101809863_726_0
 Error: gap in edge sequence at trip 103172085_101809863_1056_0
 Error: gap in edge sequence at trip 103172085_101809863_1085_0
 Process Process-1:
 Traceback (most recent call last):
   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
     self.run()
   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
     self._target(*self._args, **self._kwargs)
   File "./tsc_main.py", line 398, in simulation_request
     options.script_module.post(options, params, conn, final_routes)
   File "/usr/share/sumo/tools/sumolib/miscutils.py", line 41, in benchmark_wrapper
     result = func(*args, **kwargs)
   File "scenario_templates/berlin_net/__init__.py", line 21, in post
     procs = [postprocess.run_pedestrian_sumo(options, routefile),
   File "/mnt/SUMO/tsc/postprocess.py", line 177, in run_pedestrian_sumo
     sim_start, sim_end = create_personfile(options.mapped_trips, routefile, personfile)
   File "/usr/share/sumo/tools/sumolib/miscutils.py", line 41, in benchmark_wrapper
     result = func(*args, **kwargs)
   File "/mnt/SUMO/tsc/postprocess.py", line 136, in create_personfile
     route, vtype = routes[uid]
 KeyError: '103725003_102110202_334_0'
`

**Comment by behrisch** [comment]
person trip postprocessing is currently broken and has currently no use case

**Comment by behrisch** [comment]
post processing has been removed from the berlin net
