### ISSUE TITLE
install_scenario_templates.py error when directory scenario_templates is already created

### ISSUE THREAD

**Issue by ArmelliniMG** [DLR-TS/tsc#24]
If the directory with the scenarios was already created, the script cannot copy the file in the folder if it already exists. (see line 166 in the script)

Here the error on windows:
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: '\\tsc\\scenario_templates\\berlin_net\\tmp_output\\**1_net.net.xml.gz**' -> '\\tsc\\scenario_templates\\berlin_net\\**net.net.xml.gz**'

If the files cannot be updated, this may lead to errors in the simulation. For example, if the new berlin network cannot be generated due to an error in netconvert, the script will take the oldest files and the user may not notice this, as the netconvert messages are very large.

**Comment by behrisch** [comment]
works on linux, but not on windows

**Comment by behrisch** [comment]
we should redirect netconvert outputs to the log as well (and suppress them on the terminal), to make the warnings about existing directories more prominent
