### ISSUE TITLE
add taxi stand import to installation process

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/tsc#25]
python script already exists in sumo but needs to be called

**Comment by behrisch** [comment]
corresponding idling algorithm still nneds to be implemented in SUMO (not urgent we mostly need them as starting place)

**Comment by behrisch** [comment]
fixed in e61235f4f68e285c39c53414a66e72169a94bcc8 (idling algorithm is still open see eclipse/sumo#6418

**Comment by alviraat** [comment]
How can I implement the idling algorithm, also select the best parking for taxi vehicles with device taxi?

**Comment by namdre** [comment]
@alviraat This is the wrong repository for your request. See https://github.com/eclipse-sumo/sumo/issues/16387
