### ISSUE TITLE
netconvert fails building the berlin-net scenario

### ISSUE THREAD

**Issue by m-kro** [DLR-TS/tsc#47]
Running  `./install_scenario_templates.py -c postgres.tsccfg` as given in the readme file, I get a netconvert error regarding the berlin-net scenario:

> Error: Edge's '24599308-AddedOffRampEdge' to-node '6561995746' is not known.
> Repeating initial error messages:
> The connection-source edge '761308715' is not known.
> Edge's '24599308-AddedOffRampEdge' to-node '6561995746' is not known.
> Quitting (on error).

**Comment by behrisch** [comment]
for some reason the junction seems to get joined now loosing the edge in question

**Comment by behrisch** [comment]
It was another issue of eclipse/sumo#10732 because I accidentally disabled ptline output
